CREATE USER ANY_DEV IDENTIFIED BY "anympass";
GRANT "DBA" TO ANY_DEV;
GRANT "CONNECT" TO ANY_DEV;
ALTER USER ANY_DEV DEFAULT ROLE "DBA","CONNECT";

CREATE TABLE ANY_DEV."db_version"
(
  "db_version"   VARCHAR2(256) NOT NULL,
  "ts_timestamp" TIMESTAMP(6) DEFAULT SYSTIMESTAMP NOT NULL,
  "description"  VARCHAR2(2048) NOT NULL
);

-- alter user ANY_DEV identified by anympass ACCOUNT UNLOCK;
-- REVOKE CREATE TABLE FROM ANY_DEV;